version: '3'
services:
  app:
    container_name: utils-node-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: